spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aicopilot
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.aicopilot: DEBUG